version: '3.9'

services:
  ipa:
    image: freeipa/freeipa-server:rocky-9-4.10.1
    ports:
      - 80:80
      - 443:443
      - 389:389
      - 636:636
      - 88:88
      - 464:464
      - 88:88/udp
      - 464:464/udp
      - 123:123/udp
    cap_add:
      - SYS_TIME
      - NET_ADMIN
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv6.conf.lo.disable_ipv6=0
    security_opt:
      - "seccomp:unconfined"
    restart: unless-stopped
    volumes:
      - /opt/freeipa/data:/data
      - /opt/freeipa/logs:/logs